spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9901
          zk-nodes: localhost:2182
    config:
      server:
        git:
          uri: https://github.com/bluecitymoon/cloud-conf.git

server:
  port: 9999

security:
  user:
    password: SpingCloudConfiguration

